// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type CartItem struct {
	ItemID   int32
	ItemName string
	Price    float64
	Quantity int32
}

type Product struct {
	ProductID   int32
	ProductName string
	Price       float64
	Stock       int32
}
